language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt # install package + test dependencies
script:
  - py.test app/test/afke_tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls