language: python
python:
  - 3.9
before_install:
  - pip install poetry
install:
  - poetry install # install packages + test dependencies
script: pytest --cov # run tests
after_success:
  - coveralls