version: "3.7"

services:
    application:
        container_name: ubademy-back-py
        build:
            context: .
        volumes:
            - .:/opt/application/ubademy-back-py
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - postgres-db
    postgres-db:
        container_name: pgdb
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./app/postgres:/ubademydb
        environment:
            POSTGRES_USER: fake
            POSTGRES_PASSWORD: "1234321"
            POSTGRES_DB: ubademy
            PGDATA: /appdb
