version: "3.7"

services:
    application:
        container_name: ubademy-back-py
        build:
            context: .
        volumes:
            - .:/opt/application/ubademy-back-py
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - postgres-db
            - datadog-agent
    postgres-db:
        container_name: pgdb
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./app/postgres:/ubademydb
        environment:
            POSTGRES_USER: fake
            POSTGRES_PASSWORD: "1234321"
            POSTGRES_DB: ubademy
            PGDATA: /appdb
    datadog-agent:
        container_name: datadog-agent
        image: datadog/agent:latest
        environment:
            - DD_API_KEY=${DATADOG_API_KEY}
            - DD_SITE=${DATADOG_SITE:-datadoghq.com}
            - DD_HOSTNAME=${HOSTNAME}
            - DD_LOGS_ENABLED=true
            #- DD_PROCESS_AGENT_ENABLED=true
            - DD_APM_ENABLED=true
            - NON_LOCAL_TRAFFIC=true
#            - DD_BIND_HOST=0.0.0.0
        ports:
            - "8126:8126/tcp"
        volumes:
            # Logs are collected from container stdout/stderr from the Docker socket.
            - /var/run/docker.sock:/var/run/docker.sock:ro
