"""init user and course dbs + added creator of course, collaborator relationship and students relationship talbes

Revision ID: 15d39f9984b6
Revises: 
Create Date: 2021-10-18 00:35:37.934106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d39f9984b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=False)
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_user_id'), 'user_account', ['user_id'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('length', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('creator_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_subject'), 'course', ['subject'], unique=False)
    op.create_table('collaborator',
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('student',
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('collaborator')
    op.drop_index(op.f('ix_course_subject'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_account_user_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
