"""extra info on student table

Revision ID: 1a955adcdbfc
Revises: 8b17af98717a
Create Date: 2021-11-18 22:51:30.970363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a955adcdbfc'
down_revision = '8b17af98717a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.Integer(), primary_key=True, nullable=False))
    op.add_column('student', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('current_lesson', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('student', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student', sa.Column('grade', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_column('student', 'grade')
    op.drop_column('student', 'end_date')
    op.drop_column('student', 'start_date')
    op.drop_column('student', 'current_lesson')
    op.drop_column('student', 'active')
    op.drop_column('student', 'id')
    # ### end Alembic commands ###
