"""added deletes on cascade

Revision ID: 230398c3b7e0
Revises: cb5da1e602f3
Create Date: 2021-10-28 23:14:46.236685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230398c3b7e0'
down_revision = 'cb5da1e602f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choice_multiple_choice_question_id_fkey', 'choice', type_='foreignkey')
    op.create_foreign_key(None, 'choice', 'multiple_choice_question', ['multiple_choice_question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('develop_question_question_id_fkey', 'develop_question', type_='foreignkey')
    op.create_foreign_key(None, 'develop_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lesson_course_id_fkey', 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('multiple_choice_question_question_id_fkey', 'multiple_choice_question', type_='foreignkey')
    op.create_foreign_key(None, 'multiple_choice_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_exam_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_exam_id_fkey', 'question', 'exam', ['exam_id'], ['id'])
    op.drop_constraint(None, 'multiple_choice_question', type_='foreignkey')
    op.create_foreign_key('multiple_choice_question_question_id_fkey', 'multiple_choice_question', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key('lesson_course_id_fkey', 'lesson', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'develop_question', type_='foreignkey')
    op.create_foreign_key('develop_question_question_id_fkey', 'develop_question', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'choice', type_='foreignkey')
    op.create_foreign_key('choice_multiple_choice_question_id_fkey', 'choice', 'multiple_choice_question', ['multiple_choice_question_id'], ['id'])
    # ### end Alembic commands ###
