"""rename student table

Revision ID: 38757e853e8a
Revises: 1a955adcdbfc
Create Date: 2021-11-19 20:55:04.961268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38757e853e8a'
down_revision = '1a955adcdbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enroll_course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('current_lesson', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'course_id')
    )
    op.create_index(op.f('ix_enroll_course_id'), 'enroll_course', ['id'], unique=False)
    op.drop_index('ix_student_id', table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('current_lesson', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='student_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], name='student_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='student_pkey')
    )
    op.create_index('ix_student_id', 'student', ['id'], unique=False)
    op.drop_index(op.f('ix_enroll_course_id'), table_name='enroll_course')
    op.drop_table('enroll_course')
    # ### end Alembic commands ###
