"""added subscription and user subscription entities

Revision ID: 43cb77898ee1
Revises: 38757e853e8a
Create Date: 2021-11-21 13:16:56.638287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cb77898ee1'
down_revision = '38757e853e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### Added subscription values to entity
    op.execute("INSERT INTO subscription(title, price) VALUES ('Free', 0.0)")
    op.execute("INSERT INTO subscription(title, price) VALUES ('Gold', 10.0)")
    op.execute("INSERT INTO subscription(title, price) VALUES ('Premium', 50.0)")
    # ####

    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_title'), 'subscription', ['title'], unique=False)
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'subscription_id')
    )
    op.create_index(op.f('ix_user_subscription_id'), 'user_subscription', ['id'], unique=False)
    op.drop_column('user_account', 'subscription')
    # ### Set default Free subscription to existing users
    op.execute("INSERT INTO user_subscription(user_id, subscription_id, active) "
               "SELECT DISTINCT user_id, 1, true from user_account")
    # Added to be consistent with existing data on table
    op.execute("UPDATE user_subscription SET subscription_id = (SELECT id FROM subscription WHERE title='Free')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_subscription_id'), table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_index(op.f('ix_subscription_title'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
