"""init modification of collaborator relationship table

Revision ID: 534f0aa2f556
Revises: f46d0d90262d
Create Date: 2021-12-02 15:35:35.649061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534f0aa2f556'
down_revision = 'f46d0d90262d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborator', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))
    op.add_column('collaborator', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('collaborator', sa.Column('start_date', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.add_column('collaborator', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_collaborator_id'), 'collaborator', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborator_id'), table_name='collaborator')
    op.drop_column('collaborator', 'end_date')
    op.drop_column('collaborator', 'start_date')
    op.drop_column('collaborator', 'active')
    op.drop_column('collaborator', 'id')
    # ### end Alembic commands ###
