"""add active property to exam entity

Revision ID: 8b17af98717a
Revises: 43da115dd3f4
Create Date: 2021-11-18 19:47:52.178433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b17af98717a'
down_revision = '43da115dd3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('active', sa.Boolean(), nullable=True))
    # Added to be consistent with existing data on table
    op.execute("UPDATE exam SET active = false")
    op.alter_column('exam', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'active')
    # ### end Alembic commands ###
