"""added subscription_id_required to course table

Revision ID: ab2d2638ee71
Revises: 534f0aa2f556
Create Date: 2021-12-05 22:59:35.242065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2d2638ee71'
down_revision = '534f0aa2f556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('subscription_id_required', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'subscription', ['subscription_id_required'], ['id'])
    # Added to be consistent with existing data on table
    op.execute("UPDATE course SET subscription_id_required = (SELECT id FROM subscription WHERE title='Free')")
    op.alter_column('course', 'subscription_id_required', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'subscription_id_required')
    # ### end Alembic commands ###
