"""added enroll_course_exam table to relate student enroll to a course to a taken exam

Revision ID: d9dc732d614e
Revises: 43cb77898ee1
Create Date: 2021-11-26 16:17:00.044370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dc732d614e'
down_revision = '43cb77898ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enroll_course_id', table_name='enroll_course')
    op.create_index(op.f('ix_enroll_course_id'), 'enroll_course', ['id'], unique=True)
    op.drop_index('ix_exam_id', table_name='exam')
    op.create_index(op.f('ix_exam_id'), 'exam', ['id'], unique=True)

    op.create_table('enroll_course_exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enroll_course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enroll_course_id'], ['enroll_course.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id', 'enroll_course_id', 'lesson_id', 'exam_id')
    )
    op.create_index(op.f('ix_enroll_course_exam_id'), 'enroll_course_exam', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enroll_course_exam_id'), table_name='enroll_course_exam')
    op.drop_table('enroll_course_exam')
    op.drop_index(op.f('ix_exam_id'), table_name='exam')
    op.create_index('ix_exam_id', 'exam', ['id'], unique=False)
    op.drop_index(op.f('ix_enroll_course_id'), table_name='enroll_course')
    op.create_index('ix_enroll_course_id', 'enroll_course', ['id'], unique=False)
    # ### end Alembic commands ###
