"""added some user profile information to user schema

Revision ID: ffea6616a1aa
Revises: 230398c3b7e0
Create Date: 2021-11-06 19:28:12.597594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffea6616a1aa'
down_revision = '230398c3b7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user_account', sa.Column('phone_type', sa.String(length=20), nullable=True))
    op.add_column('user_account', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('user_account', sa.Column('subscription', sa.String(length=50), nullable=True))
    op.add_column('user_account', sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # Added to be consistent with existing data on table
    op.execute("UPDATE user_account SET subscription = 'Base'")
    op.alter_column('user_account', 'subscription', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'creation_date')
    op.drop_column('user_account', 'subscription')
    op.drop_column('user_account', 'phone_number')
    op.drop_column('user_account', 'phone_type')
    op.drop_column('user_account', 'birth_date')
    # ### end Alembic commands ###
